# Generated by Django 3.1.7 on 2021-03-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210312_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='tarif',
            field=models.IntegerField(choices=[(0, 'No Tar'), (1, 'First Tar'), (2, 'Second Tar'), (3, 'Third Tar')], default=0),
        ),
    ]
