# Generated by Django 3.1.7 on 2021-03-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210312_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='None/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metauser')),
            ],
        ),
    ]
