# Generated by Django 3.1.7 on 2021-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='Lorem Ipsum', max_length=1000),
        ),
    ]
