# Generated by Django 3.1.7 on 2021-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='itype',
            field=models.CharField(default='pass', max_length=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='UserImages/'),
        ),
    ]
