# Generated by Django 3.1.7 on 2021-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210312_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metauser',
            name='company',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='company',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
